const menu = document.querySelector('.menu');
menu.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') !== 'true'; menu.setAttribute('aria-expanded', String(open)); document.querySelector('#navigation').classList.toggle('open', open); });
document.querySelectorAll('#navigation a').forEach(link => link.addEventListener('click', () => { menu.setAttribute('aria-expanded', 'false'); document.querySelector('#navigation').classList.remove('open'); }));
document.querySelectorAll('.swatches button').forEach(button => button.addEventListener('click', () => { document.querySelector('#editable-preview').style.color = button.dataset.color; document.querySelectorAll('.swatches button').forEach(b => b.setAttribute('aria-pressed', String(b === button))); }));
document.querySelector('#prompt-form').addEventListener('submit', event => { event.preventDefault(); const idea = document.querySelector('#site-prompt').value.trim(); window.location.href = 'ai-studio.html' + (idea ? '?b=' + encodeURIComponent(idea) : ''); });
const features = {
 revenue: ['Build once. Earn every month.', 'Bill clients monthly for hosting + maintenance. Build lasting relationships and an income that keeps growing — yours to keep.', '$2,400', 'potential client value / year'],
 preview: ['A link. A great first impression.', 'Share a preview with your client before launch. Get everyone on the same page, gather feedback, and move from first draft to final approval.', 'One link', 'to share your next big idea'],
 domains: ['Your brand. Your own address.', 'Make your website feel right at home with a custom domain. Keep your business name front and center, from the first click to the last.', '100% you', 'your name on the web'],
 hosting: ['You create. We handle the rest.', 'Keep your focus on the creative work. Ask our team about hosting and publishing your website, so you can launch with confidence.', 'Go live', 'without the technical headache'],
 revisions: ['Great ideas deserve another draft.', 'Try a new direction. Refine your message. Explore a different palette. Keep shaping your website until it feels like your business.', 'Make it yours', 'one thoughtful edit at a time']
};
const tabs = [...document.querySelectorAll('[data-feature]')];
tabs.forEach((tab, index) => { tab.id = 'tab-' + tab.dataset.feature; tab.setAttribute('aria-controls', 'feature-panel'); tab.tabIndex = tab.getAttribute('aria-selected') === 'true' ? 0 : -1; tab.addEventListener('click', () => { tabs.forEach(t => { t.setAttribute('aria-selected', String(t === tab)); t.tabIndex = t === tab ? 0 : -1; }); const data = features[tab.dataset.feature]; ['feature-title', 'feature-description', 'feature-value', 'feature-caption'].forEach((id, i) => document.getElementById(id).textContent = data[i]); document.querySelector('.feature-panel').setAttribute('aria-labelledby', tab.id); }); tab.addEventListener('keydown', e => { if (['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) { e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? tabs.length - 1 : (index + (e.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; tabs[next].focus(); tabs[next].click(); } }); });
document.querySelector('.feature-panel').id = 'feature-panel'; document.querySelector('.feature-panel').setAttribute('aria-labelledby', 'tab-revenue');
const datasets = { 'Yoga studios': ['Lotus & Linen', 'Mat & Mantra', 'Sunrise Flow', 'Stillwater'], 'Coffee shops': ['Oak & Ember', 'The Daily Grind', 'Morning Ritual', 'Little Bird Coffee'], 'Hair salons': ['The Sunday Salon', 'Root & Bloom', 'Good Hair Studio', 'The Cutting Room'] };
let currentLeads = [];
function renderLeads() { const type = document.querySelector('#business-type').value; const location = document.querySelector('#location').value.trim(); if (!location) return; currentLeads = datasets[type].map((name, i) => ({name, location, phone: `(512) 555-014${i + 2}`, website: i === 2, rating: i % 2 ? '4.8' : '4.7'})); const target = document.querySelector('#lead-results'); target.replaceChildren(); currentLeads.forEach(lead => { const row = document.createElement('div'); row.className = 'lead-row'; const avatar = document.createElement('span'); avatar.className = 'lead-avatar'; avatar.textContent = lead.name.split(' ').filter(w => w !== '&').map(w => w[0]).slice(0, 2).join(''); const info = document.createElement('div'); info.className = 'lead-name'; const name = document.createElement('b'); name.textContent = lead.name; const phone = document.createElement('small'); phone.textContent = lead.phone; info.append(name, phone); const rating = document.createElement('span'); rating.className = 'lead-rating'; rating.textContent = '★ ' + lead.rating; row.append(avatar, info, rating); if (!lead.website) { const badge = document.createElement('span'); badge.className = 'no-site'; badge.textContent = 'No website'; row.append(badge); } target.append(row); }); document.querySelector('#result-count').textContent = '4 sample results · 3 no-website'; }
renderLeads();
document.querySelector('#lead-form').addEventListener('submit', e => { e.preventDefault(); renderLeads(); toast('Sample results updated for ' + document.querySelector('#location').value.trim()); });
document.querySelector('#open-finder').addEventListener('click', () => { document.querySelector('.leads-card').scrollIntoView({behavior: 'smooth', block: 'center'}); document.querySelector('#business-type').focus({preventScroll:true}); });
let toastTimeout; function toast(text) { const el = document.querySelector('#toast'); el.textContent = text; el.classList.add('visible'); clearTimeout(toastTimeout); toastTimeout = setTimeout(() => el.classList.remove('visible'), 3500); }
document.querySelector('#csv-button').addEventListener('click', () => { const escape = text => '"' + String(text).replace(/^[=+@-]/, "'$&").replaceAll('"', '""') + '"'; const rows = [['Business', 'Location', 'Phone', 'Has website', 'Data source'], ...currentLeads.map(l => [l.name, l.location, l.phone, l.website ? 'Yes' : 'No', 'Demo sample'])]; const blob = new Blob([rows.map(row => row.map(escape).join(',')).join('\r\n')], {type:'text/csv;charset=utf-8;'}); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'nexaflow-sample-leads.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast('Sample leads exported as CSV.'); });
document.querySelector('#invoice-print').addEventListener('click', () => { document.querySelector('.print-invoice')?.remove(); const printable = document.createElement('div'); printable.className = 'print-invoice'; printable.style.display = 'none'; printable.append(document.querySelector('.invoice-card').cloneNode(true)); printable.querySelectorAll('[id]').forEach(el => el.removeAttribute('id')); document.body.append(printable); window.print(); });
